import React, { createContext, useContext, useState } from 'react'
import AsyncStorage from '@react-native-async-storage/async-storage'

type Langue = 'fr' | 'pt'

const T = {
  fr: {
    aujourdhui: "Aujourd'hui",
    historique: 'Historique',
    fichePaye: 'Fiche Paye',
    reglages: 'Réglages',
    bonjour: 'Bonjour',
    demarrer: 'DÉMARRER',
    pause: 'PAUSE',
    reprendre: 'REPRENDRE',
    terminer: 'TERMINER',
    enService: 'EN SERVICE',
    enPause: 'EN PAUSE',
    enConduite: 'EN CONDUITE',
    attente: "En attente de mouvement...",
    avantPause: 'Avant pause obligatoire',
    pauseObligatoire: 'Pause obligatoire maintenant !',
    pauseDans: 'Pause dans',
    decouche: 'DÉCOUCHÉ CE SOIR',
    decoucheSub: 'Frais appliqués automatiquement',
    limitesLegales: 'LIMITES LÉGALES',
    conduiteAujourdhui: "Conduite aujourd'hui",
    serviceJournalier: 'Service journalier',
    amplitudeJournaliere: 'Amplitude journalière',
    semaineEnCours: 'Semaine en cours',
    conduite: 'Conduite',
    service: 'Service',
    amplitude: 'Amplitude',
    decouch: 'Découché',
    frais: 'Frais',
    jours: 'Jours',
    terminerConfirm: 'Terminer ?',
    terminerMsg: 'Confirmes-tu la fin de service ?',
    annuler: 'Annuler',
    serviceTermine: '✅ Service terminé',
    conduiteGelée: 'conduite (gelée)',
    serviceGele: 'service (gelé)',
    pauseValide: '✅ Pause valide — compteur conduite va se réinitialiser',
    pauseEnCours: 'pause en cours',
    semaine: 'Semaine',
    mois: 'Mois',
    resumeSemaine: 'RÉSUMÉ DE LA SEMAINE',
    resumeMois: 'RÉSUMÉ DU MOIS',
    aucunService: 'Aucun service enregistré',
    joursTermines: 'Les jours terminés apparaîtront ici',
    exporterRapport: '📤 Exporter le rapport',
    detailJours: 'DÉTAIL DES JOURS',
    monProfil: 'MON PROFIL',
    typeConducteur: 'TYPE DE CONDUCTEUR',
    apparence: 'APPARENCE',
    modeSombre: 'Mode sombre',
    themeFonce: 'Thème foncé / clair',
    langue: 'LANGUE',
    notifications: 'NOTIFICATIONS',
    alertesPause: 'Alertes pause obligatoire',
    rappelPause: 'Rappel avant 4h30 de conduite',
    abonnement: 'ABONNEMENT',
    joursEssai: "jours d'essai restants",
    sabonner: "S'abonner — 2,99€/mois",
    mesDonnees: 'MES DONNÉES',
    effacerHistorique: "Effacer l'historique",
    supprimeTousJours: 'Supprime tous les jours enregistrés',
    reinitialiserApp: "Réinitialiser l'app",
    effaceToutesDonnees: 'Efface toutes les données',
    ficheDePaye: 'Fiche de Paye',
    bulletinActivite: "Bulletin + Activité — tout en un coup d'œil",
    changerProfil: 'Changer de profil',
    modeNuitActive: '🌙 Mode nuit activé',
    modeNuitMsg: 'Démarrage entre 21h et 6h détecté.\nLimites ajustées:\n• Service: 10h max\n• Amplitude: 13h max',
    localisationNecessaire: '📍 Localisation nécessaire',
    localisationMsg: 'TachoMax a besoin de ta localisation pour détecter automatiquement quand tu conduis (>5km/h).',
    ok: 'OK',
    modeNuitBandeau: '🌙 Mode nuit · Limites ajustées · Service 10h · Amplitude 13h',
    aApprendrePatrao: 'Apprentissage en cours',
    adicionaMeses: 'Ajoute des mois pour activer la prévision',
    moisAAjouter: 'MOIS À AJOUTER',
    carregaDocumentos: "Charge les documents disponibles — n'importe quel mois",
    ficheLabel: 'fiche',
    fraisLabel: 'frais',
    emFalta: 'manquant',
    oQueCarregar: 'Que charger maintenant?',
    ficheDePayeTitle: 'FICHE DE PAYE',
    boletimFraisTitle: 'BOLETIM DE FRAIS',
    sugerido: 'Suggéré',
    ouQualquerMes: "ou n'importe quel autre mois",
    selecionarFiche: '📄 Sélectionner fiche de paye',
    selecionarFrais: '🧾 Sélectionner boletim de frais',
    jpgHint: "JPG · PNG · jusqu'à 5 pages · n'importe quel mois",
    pdfHint: "PDF · IMG · jusqu'à 3 fichiers · n'importe quel mois",
    ficheCarregada: '✅ Fiche chargée!',
    fraisCarregado: '✅ Frais chargé!',
    agoraFrais: 'Charge maintenant le boletim de frais pour continuer.',
    agoraFiche: 'Charge maintenant la fiche de paye pour continuer.',
    quantoRecebeste: 'COMBIEN AS-TU REÇU EN TOUT CE MOIS? (€)',
    diaSalario: 'JOUR DU SALAIRE',
    diaFrais: 'JOUR DES FRAIS',
    guardar: '✅ Enregistrer',
    netPaye: 'Net payé',
    totalFrais: 'Total frais',
    recebido: 'reçu',
    decoucheOui: 'OUI ✅',
    decoucheNon: 'NON',
    decoucheTerminer: '🌙 Terminer (Découché)',
    decoucheBtn: '🌙 Découché',
    paradoMsg: 'Arrêté depuis +20min — en pause?',
    paradoSim: '✅ Oui',
    paradoNao: '❌ Non',
    gpsAlert: '⚠️ GPS sans signal — vérifie la localisation',
    pausasHoje: 'Pauses aujourd\'hui:',
  },
  pt: {
    aujourdhui: 'Hoje',
    historique: 'Histórico',
    fichePaye: 'Ficha Salário',
    reglages: 'Definições',
    bonjour: 'Bom dia',
    demarrer: 'INICIAR',
    pause: 'PAUSA',
    reprendre: 'RETOMAR',
    terminer: 'TERMINAR',
    enService: 'EM SERVIÇO',
    enPause: 'EM PAUSA',
    enConduite: 'A CONDUZIR',
    attente: 'À espera de movimento...',
    avantPause: 'Antes da pausa obrigatória',
    pauseObligatoire: 'Pausa obrigatória agora!',
    pauseDans: 'Pausa em',
    decouche: 'PERNOITA ESTA NOITE',
    decoucheSub: 'Despesas aplicadas automaticamente',
    limitesLegales: 'LIMITES LEGAIS',
    conduiteAujourdhui: 'Condução hoje',
    serviceJournalier: 'Serviço diário',
    amplitudeJournaliere: 'Amplitude diária',
    semaineEnCours: 'Semana em curso',
    conduite: 'Condução',
    service: 'Serviço',
    amplitude: 'Amplitude',
    decouch: 'Pernoita',
    frais: 'Despesas',
    jours: 'Dias',
    terminerConfirm: 'Terminar?',
    terminerMsg: 'Confirmas o fim do serviço?',
    annuler: 'Cancelar',
    serviceTermine: '✅ Serviço terminado',
    conduiteGelée: 'condução (parada)',
    serviceGele: 'serviço (parado)',
    pauseValide: '✅ Pausa válida — contador de condução vai reiniciar',
    pauseEnCours: 'pausa em curso',
    semaine: 'Semana',
    mois: 'Mês',
    resumeSemaine: 'RESUMO DA SEMANA',
    resumeMois: 'RESUMO DO MÊS',
    aucunService: 'Nenhum serviço registado',
    joursTermines: 'Os dias terminados aparecerão aqui',
    exporterRapport: '📤 Exportar relatório',
    detailJours: 'DETALHE DOS DIAS',
    monProfil: 'MEU PERFIL',
    typeConducteur: 'TIPO DE CONDUTOR',
    apparence: 'APARÊNCIA',
    modeSombre: 'Modo escuro',
    themeFonce: 'Tema escuro / claro',
    langue: 'LÍNGUA',
    notifications: 'NOTIFICAÇÕES',
    alertesPause: 'Alertas pausa obrigatória',
    rappelPause: 'Lembrete antes de 4h30 de condução',
    abonnement: 'SUBSCRIÇÃO',
    joursEssai: 'dias de teste restantes',
    sabonner: 'Subscrever — 2,99€/mês',
    mesDonnees: 'OS MEUS DADOS',
    effacerHistorique: 'Apagar histórico',
    supprimeTousJours: 'Apaga todos os dias registados',
    reinitialiserApp: 'Reinicializar a app',
    effaceToutesDonnees: 'Apaga todos os dados',
    ficheDePaye: 'Ficha de Salário',
    bulletinActivite: 'Boletim + Actividade — tudo num relance',
    changerProfil: 'Mudar de perfil',
    modeNuitActive: '🌙 Modo noturno activado',
    modeNuitMsg: 'Início entre 21h e 6h detectado.\nLimites ajustados:\n• Serviço: 10h máx\n• Amplitude: 13h máx',
    localisationNecessaire: '📍 Localização necessária',
    localisationMsg: 'TachoMax precisa da tua localização para detectar automaticamente quando conduz (>5km/h).',
    ok: 'OK',
    modeNuitBandeau: '🌙 Modo noturno · Limites ajustados · Serviço 10h · Amplitude 13h',
    aApprendrePatrao: 'A aprender o teu padrão',
    adicionaMeses: 'Adiciona meses para activar a previsão',
    moisAAjouter: 'MESES A ADICIONAR',
    carregaDocumentos: 'Carrega os documentos que tens disponíveis — qualquer mês',
    ficheLabel: 'fiche',
    fraisLabel: 'frais',
    emFalta: 'em falta',
    oQueCarregar: 'O que carregar agora?',
    ficheDePayeTitle: 'FICHE DE PAYE',
    boletimFraisTitle: 'BOLETIM DE FRAIS',
    sugerido: 'Sugerido',
    ouQualquerMes: 'ou qualquer outro mês',
    selecionarFiche: '📄 Selecionar fiche de paye',
    selecionarFrais: '🧾 Selecionar boletim de frais',
    jpgHint: 'JPG · PNG · até 5 páginas · qualquer mês',
    pdfHint: 'PDF · IMG · até 3 ficheiros · qualquer mês',
    ficheCarregada: '✅ Fiche carregada!',
    fraisCarregado: '✅ Frais carregado!',
    agoraFrais: 'Agora carrega o boletim de frais para continuar.',
    agoraFiche: 'Agora carrega a fiche de paye para continuar.',
    quantoRecebeste: 'QUANTO RECEBESTE NO TOTAL ESTE MÊS? (€)',
    diaSalario: 'DIA DO SALÁRIO',
    diaFrais: 'DIA DOS FRAIS',
    guardar: '✅ Guardar',
    netPaye: 'Net payé',
    totalFrais: 'Total frais',
    recebido: 'recebido',
    decoucheOui: 'SIM ✅',
    decoucheNon: 'NÃO',
    decoucheTerminer: '🌙 Terminar (Pernoita)',
    decoucheBtn: '🌙 Pernoita',
    paradoMsg: 'Estás parado há +20min — em pausa?',
    paradoSim: '✅ Sim',
    paradoNao: '❌ Não',
    gpsAlert: '⚠️ GPS sem sinal — verifica a localização',
    pausasHoje: 'Pausas hoje:',
  }
}

type LangueContextType = {
  langue: Langue
  t: typeof T.fr
  setLangue: (l: Langue) => void
}

const LangueContext = createContext<LangueContextType>({
  langue: 'fr',
  t: T.fr,
  setLangue: () => {},
})

export function LangueProvider({ children }: { children: React.ReactNode }) {
  const [langue, setLangueState] = useState<Langue>('fr')

  const setLangue = async (l: Langue) => {
    setLangueState(l)
    await AsyncStorage.setItem('langue', l)
  }

  React.useEffect(() => {
    AsyncStorage.getItem('langue').then(l => {
      if (l === 'fr' || l === 'pt') setLangueState(l)
    })
  }, [])

  return (
    <LangueContext.Provider value={{ langue, t: T[langue], setLangue }}>
      {children}
    </LangueContext.Provider>
  )
}

export const useLangue = () => useContext(LangueContext)
