/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/fiche` | `/fiche`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historique` | `/historique`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LangueContext` | `/LangueContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reglages` | `/reglages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ThemeContext` | `/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ThemeProvider` | `/ThemeProvider`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/fiche` | `/fiche`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/historique` | `/historique`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LangueContext` | `/LangueContext`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/onboarding` | `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reglages` | `/reglages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ThemeContext` | `/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ThemeProvider` | `/ThemeProvider`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/fiche${`?${string}` | `#${string}` | ''}` | `/fiche${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/historique${`?${string}` | `#${string}` | ''}` | `/historique${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LangueContext${`?${string}` | `#${string}` | ''}` | `/LangueContext${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reglages${`?${string}` | `#${string}` | ''}` | `/reglages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ThemeContext${`?${string}` | `#${string}` | ''}` | `/ThemeContext${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ThemeProvider${`?${string}` | `#${string}` | ''}` | `/ThemeProvider${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/fiche` | `/fiche`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historique` | `/historique`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LangueContext` | `/LangueContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reglages` | `/reglages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ThemeContext` | `/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ThemeProvider` | `/ThemeProvider`; params?: Router.UnknownInputParams; };
    }
  }
}
